# Railway configuration for Python backend
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python route_optimization_server.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.environment]
PYTHON_VERSION = "3.10.12"
